### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by hrqmonteiro** [Rolando-Barbella/online-dev-cv#1]
```
Unhandled Runtime Error
TypeError: Cannot read property 'items' of undefined

pages/index.js (20:57) @ _callee$

  18 |   });
  19 |   setIsLoading(false);
> 20 |   setListMainDetails(mainDetails.data.listMainDetailss.items[0]);
     |                                                       ^
  21 | }
  22 | if(isLoading || !mainDetails) {
  23 |   return <p>..Loading</p>
```

![print](https://user-images.githubusercontent.com/17055027/128601134-89e021e1-1bbc-4e39-b549-11d0c2c47ed4.png)

If i build it from scratch or if i clone your repo and just authenticate with my AWS credentials, i have this same error in `index.js`.

**Comment by Rolando-Barbella** [comment]
Hi @hrqmonteiro did you add data to your DB, by doing something like:

```
mutation CreateMainDetails{
    createMainDetails(input: {
      name:"Joe",
      lastName: "Satriani",
      email:"jsatriani@email.com",
      location: "Lima",
      description: "I'm Jamstack developer",
    }) {
      id
      name
      lastName
      email
      location
      description
    }
}
```

**Comment by hrqmonteiro** [comment]
> Hi @hrqmonteiro did you add data to your DB, by doing something like:
> 
> ```
> mutation CreateMainDetails{
>     createMainDetails(input: {
>       name:"Joe",
>       lastName: "Satriani",
>       email:"jsatriani@email.com",
>       location: "Lima",
>       description: "I'm Jamstack developer",
>     }) {
>       id
>       name
>       lastName
>       email
>       location
>       description
>     }
> }
> ```

Yes, but nothing happens
